import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';

import {
  BUILTIN_WORKFLOWS,
  loadBuiltinPreset,
  pipelineCommandId,
  workflowCommandPhases,
  type BuiltinWorkflow,
  type WorkspacePreset,
} from '../presets/builtinWorkflows';
import {
  backboneCommandDoc,
  CANONICAL_PHASES,
  shortcutCommandDoc,
  type CanonicalPhase,
  type WriteCommandsResult,
} from '../presets/commandModel';
import {
  providerManagedTaskCommandBody,
  PROVIDER_MANAGED_TASK_COMMAND,
} from './ProviderManagedTaskCommand';
import {
  discoverChatCommandBody,
  discoverCommandBody,
  discoverCommitCommandBody,
  discoverDevDocsCommandBody,
  discoverPipelineCommandBody,
  discoverScanCommandBody,
  DISCOVER_CHAT_COMMAND_NAME,
  DISCOVER_COMMAND_NAME,
  DISCOVER_COMMIT_COMMAND_NAME,
  DISCOVER_DEV_DOCS_COMMAND_NAME,
  DISCOVER_PIPELINE_COMMAND_NAME,
  DISCOVER_SCAN_COMMAND_NAME,
} from '../discover/DiscoverAgentCommand';
import { ModelProviderConfigStore } from '../models/ModelProviderConfigStore';
import { activeEpicsDir } from '../runs/RunState';
import { getCommandProviderAdapter } from './CommandProviderAdapter';
import { buildStepCommandSpec } from './stepCommand';

export interface SyncPipelineCommandsResult {
  commandsWritten: string[];
  providers: string[];
}

function writeCommandFile(
  file: string,
  body: string,
  overwrite: boolean,
): boolean {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  if (fs.existsSync(file) && !overwrite) { return false; }
  fs.writeFileSync(file, body, 'utf8');
  return true;
}

/** Cursor Agent slash-invokes Skills, not `.cursor/commands/*.md`. */
function writeCursorAgentSkill(
  root: string,
  commandName: string,
  rendered: string,
  overwrite: boolean,
): string | null {
  const file = path.join(root, '.cursor', 'skills', commandName, 'SKILL.md');
  return writeCommandFile(file, rendered, overwrite) ? file : null;
}

function writeRenderedCommand(
  adapter: ReturnType<typeof getCommandProviderAdapter>,
  root: string,
  commandName: string,
  rendered: string,
  overwrite: boolean,
): string[] {
  const written: string[] = [];
  const file = adapter.commandFilePath(root, commandName);
  if (writeCommandFile(file, rendered, overwrite)) written.push(file);
  if (adapter.id === 'cursor') {
    const skill = writeCursorAgentSkill(root, commandName, rendered, overwrite);
    if (skill) written.push(skill);
  }
  return written;
}

/**
 * The Discover command files are 100% generated — their Markdown contract is
 * derived from `DocSpec.ts` so it can never drift from what `mdParse.ts`
 * reads, and none of them embeds anything about a specific project. That makes
 * them the one family of command files we must *refresh*: `overwrite` is false
 * everywhere (a person's edits to a step skill are theirs to keep), which
 * would otherwise pin a workspace to whatever prompt shipped the day it was
 * set up. A stale one is not merely old — a scan prompt from before source
 * scoping existed happily reads `.aidlc/` and describes the tooling.
 *
 * So: stamp each generated file with a hash of its body, rewrite it when the
 * hash differs, and leave it alone entirely once it says `aidlc:keep` — the
 * escape hatch for anyone who does want to hand-tune one.
 */
const KEEP_MARKER = 'aidlc:keep';

function generatedStamp(commandName: string, body: string): string {
  const hash = crypto.createHash('sha256').update(body).digest('hex').slice(0, 12);
  return `<!-- aidlc:generated ${commandName} ${hash} — regenerated by the AIDLC extension. Add ${KEEP_MARKER} to this file to keep your own edits. -->`;
}

/** Whether a generated command file needs rewriting. */
function generatedCommandIsStale(file: string, stamp: string): boolean {
  let existing: string;
  try {
    existing = fs.readFileSync(file, 'utf8');
  } catch {
    return true;
  }
  if (existing.includes(KEEP_MARKER)) { return false; }
  return !existing.includes(stamp);
}

function writeStandaloneCommand(
  root: string,
  providerId: string,
  commandName: string,
  description: string,
  body: string,
  overwrite: boolean,
  mappedModel?: string,
  /** Stamp the file and refresh it whenever the generated body changes. */
  generated = false,
): string | null {
  const adapter = getCommandProviderAdapter(providerId);
  const stamped = generated ? `${body}\n${generatedStamp(commandName, body)}\n` : body;
  const rendered = adapter.renderCommandFile({
    commandName,
    description,
    body: stamped,
    epicRoot: '',
  }, mappedModel);
  const force = overwrite || (generated
    && generatedCommandIsStale(adapter.commandFilePath(root, commandName), generatedStamp(commandName, body)));
  const written = writeRenderedCommand(adapter, root, commandName, rendered, force);
  return written[0] ?? null;
}

function writeBuiltinCommandsForProvider(
  root: string,
  providerId: string,
  workflow: BuiltinWorkflow,
  preset: WorkspacePreset,
  epicRoot: string,
  overwrite: boolean,
  configStore: ModelProviderConfigStore,
): string[] {
  const adapter = getCommandProviderAdapter(providerId);
  const config = configStore.loadOrDefault();
  const written: string[] = [];

  for (const { pipelineId, phase } of workflowCommandPhases(workflow)) {
    const commandName = pipelineCommandId(pipelineId, phase.id);
    const skillBody = preset.skillContents[phase.id]
      ?? `# ${phase.name}\n\n${phase.description}\n`;
    const spec = buildStepCommandSpec(phase, skillBody, epicRoot, commandName);
    const mappedModel = configStore.mapModel(spec.canonicalModel ?? phase.model, providerId, config);
    written.push(
      ...writeRenderedCommand(
        adapter,
        root,
        commandName,
        adapter.renderCommandFile(spec, mappedModel),
        overwrite,
      ),
    );
  }
  return written;
}

export function writeTwoLayerCommandsForProvider(
  root: string,
  providerId: string,
  opts: { epicRoot?: string; phases?: CanonicalPhase[]; overwrite?: boolean } = {},
): WriteCommandsResult {
  const epicRoot = opts.epicRoot ?? 'docs/epics';
  const phases = opts.phases ?? CANONICAL_PHASES;
  const overwrite = opts.overwrite ?? false;
  const adapter = getCommandProviderAdapter(providerId);
  const configStore = new ModelProviderConfigStore(root);
  const mappedModel = configStore.modelFor(providerId);
  const written: string[] = [];
  const skipped: string[] = [];

  const emit = (commandName: string, description: string, body: string): void => {
    const file = adapter.commandFilePath(root, commandName);
    if (fs.existsSync(file) && !overwrite) { skipped.push(file); return; }
    written.push(
      ...writeRenderedCommand(
        adapter,
        root,
        commandName,
        adapter.renderCommandFile({ commandName, description, body, epicRoot }, mappedModel),
        true,
      ),
    );
  };

  emit('aidlc', 'AIDLC dispatcher', backboneCommandDoc(epicRoot));
  for (const phase of phases) {
    emit(phase.id, `${phase.description} (AIDLC ${phase.name} phase)`, shortcutCommandDoc(phase, epicRoot));
  }

  return { written, skipped };
}

export function syncProviderManagedCommandForProvider(
  root: string,
  providerId: string,
  overwrite = false,
): string[] {
  const configStore = new ModelProviderConfigStore(root);
  const mappedModel = configStore.modelFor(providerId);
  const written: string[] = [];
  for (const entry of [
    {
      name: PROVIDER_MANAGED_TASK_COMMAND.slice(1),
      description: 'Run one AIDLC task pipeline in the selected provider terminal.',
      body: providerManagedTaskCommandBody(),
    },
  ]) {
    const file = writeStandaloneCommand(
      root,
      providerId,
      entry.name,
      entry.description,
      entry.body,
      overwrite,
      mappedModel,
    );
    if (file) { written.push(file); }
  }
  return written;
}

/**
 * Install the Discover blueprint commands. Same distribution mechanism as
 * `syncProviderManagedCommandForProvider`, and like it these work without a
 * `workspace.yaml` or a delivery pipeline: a blueprint exists long before an
 * epic does.
 */
export function syncDiscoverCommandsForProvider(
  root: string,
  providerId: string,
  overwrite = false,
): string[] {
  const configStore = new ModelProviderConfigStore(root);
  const mappedModel = configStore.modelFor(providerId);
  const written: string[] = [];
  for (const entry of [
    {
      name: DISCOVER_COMMAND_NAME,
      description: `Do one step of the Discover blueprint pipeline and write its Markdown docs. Usage: /${DISCOVER_COMMAND_NAME} <step> [note]`,
      body: discoverCommandBody(),
    },
    {
      name: DISCOVER_PIPELINE_COMMAND_NAME,
      description: `Do the Discover blueprint's current step, re-detecting it each turn. Usage: /${DISCOVER_PIPELINE_COMMAND_NAME} [note]`,
      body: discoverPipelineCommandBody(),
    },
    {
      name: DISCOVER_DEV_DOCS_COMMAND_NAME,
      description: `Write the development convention docs from the chosen stack. Usage: /${DISCOVER_DEV_DOCS_COMMAND_NAME} [note]`,
      body: discoverDevDocsCommandBody(),
    },
    {
      name: DISCOVER_SCAN_COMMAND_NAME,
      description: `Reconcile one pass of Discover docs against source. Usage: /${DISCOVER_SCAN_COMMAND_NAME} pass=<1|2|3> layout=<single|parent|child> repos=<path:kind,...> brief=.aidlc/discover/scan-brief.md`,
      body: discoverScanCommandBody(),
    },
    {
      name: DISCOVER_CHAT_COMMAND_NAME,
      description: `Open a conversation about one Discover step with its docs as context. Usage: /${DISCOVER_CHAT_COMMAND_NAME} <step> [note]`,
      body: discoverChatCommandBody(),
    },
    {
      name: DISCOVER_COMMIT_COMMAND_NAME,
      description: `Stage and commit every local change in the Discover git root. Usage: /${DISCOVER_COMMIT_COMMAND_NAME} <git-root>`,
      body: discoverCommitCommandBody(),
    },
  ]) {
    const file = writeStandaloneCommand(root, providerId, entry.name, entry.description, entry.body, overwrite, mappedModel, true);
    if (file) { written.push(file); }
  }
  return written;
}

/** Sync command files for one provider (workflows that own workspace pipelines). */
export function syncPipelineCommandsForProvider(
  root: string,
  extensionPath: string,
  providerId: string,
  opts: {
    epicRoot?: string;
    overwrite?: boolean;
    configStore?: ModelProviderConfigStore;
  } = {},
): string[] {
  return syncPipelineCommandsForProviderFiltered(
    root,
    extensionPath,
    providerId,
    readWorkspacePipelineIds(root),
    opts,
  );
}

export function syncPipelineCommands(
  root: string,
  extensionPath: string,
  opts: {
    providers?: string[];
    epicRoot?: string;
    overwrite?: boolean;
    configStore?: ModelProviderConfigStore;
    /** When set, only sync workflows that own one of these pipeline ids. */
    pipelineIds?: Set<string>;
  } = {},
): SyncPipelineCommandsResult {
  const configStore = opts.configStore ?? new ModelProviderConfigStore(root);
  const config = configStore.loadOrDefault();
  const providerIds = opts.providers?.length
    ? opts.providers
    : configStore.listEnabledProviderIds(config);
  const pipelineIds = opts.pipelineIds ?? readWorkspacePipelineIds(root);

  const commandsWritten: string[] = [];
  for (const providerId of providerIds) {
    commandsWritten.push(
      ...syncPipelineCommandsForProviderFiltered(
        root,
        extensionPath,
        providerId,
        pipelineIds,
        {
          epicRoot: opts.epicRoot,
          overwrite: opts.overwrite,
          configStore,
        },
      ),
    );
  }

  return { commandsWritten, providers: providerIds };
}

function syncPipelineCommandsForProviderFiltered(
  root: string,
  extensionPath: string,
  providerId: string,
  pipelineIds: Set<string>,
  opts: {
    epicRoot?: string;
    overwrite?: boolean;
    configStore?: ModelProviderConfigStore;
  },
): string[] {
  const configStore = opts.configStore ?? new ModelProviderConfigStore(root);
  const epicRoot = opts.epicRoot ?? readEpicRootFrom(root);
  const overwrite = opts.overwrite ?? false;
  const written: string[] = [];

  for (const workflow of BUILTIN_WORKFLOWS) {
    const ownsPipeline = [
      workflow.pipelineId,
      ...(workflow.additionalPipelines ?? []).map((a) => a.id),
    ].some((id) => pipelineIds.has(id));
    if (!ownsPipeline) { continue; }

    let preset: WorkspacePreset;
    try {
      preset = loadBuiltinPreset(extensionPath, workflow);
    } catch {
      continue;
    }
    written.push(
      ...writeBuiltinCommandsForProvider(
        root,
        providerId,
        workflow,
        preset,
        epicRoot,
        overwrite,
        configStore,
      ),
    );
  }

  // The provider-managed task command is available even before a workspace
  // has a delivery pipeline, so every provider gets its native command file.
  written.push(...syncProviderManagedCommandForProvider(root, providerId, overwrite));

  // Same reasoning for the Discover commands — a blueprint is usable from the
  // first sentence the user types, long before any pipeline exists.
  written.push(...syncDiscoverCommandsForProvider(root, providerId, overwrite));

  if (pipelineIds.size > 0) {
    const twoLayer = writeTwoLayerCommandsForProvider(root, providerId, { epicRoot, overwrite });
    written.push(...twoLayer.written);
  }

  return written;
}

function readWorkspacePipelineIds(root: string): Set<string> {
  try {
    const file = path.join(root, '.aidlc', 'workspace.yaml');
    if (!fs.existsSync(file)) { return new Set(); }
    const doc = yaml.load(fs.readFileSync(file, 'utf8')) as { pipelines?: Array<{ id?: unknown }> } | null;
    const ids = new Set<string>();
    for (const p of doc?.pipelines ?? []) {
      if (typeof p.id === 'string') { ids.add(p.id); }
    }
    return ids;
  } catch {
    return new Set();
  }
}

function readEpicRootFrom(root: string): string {
  return activeEpicsDir(root);
}

export { PROVIDER_MANAGED_TASK_COMMAND };
